[package]
authors = ["archer884"]
edition = "2018"
name = "roll-report"
version = "0.1.0"

[dependencies]
clap = { version = "3.0.0-beta.2" }
hashbrown = "*"
rollstat = { git = "https://github.com/archer884/rollstat/" }
